#!/usr/bin/env bash
set -e
export DB_MANAGER_WORKDIR=/var/dbManager
. "$DB_MANAGER_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
DB Manager
Version: $(cat $DB_MANAGER_WORKDIR/VERSION)
Usage: $cli_name [command]
Commands:
  create    create database
  drop      drop   database
  view      view databases and users
  sync      sync databases
  user      create,delete users
  restore   restore a database from dump
  access    grant,revoke user access to database
  exist     check if a database exists
  *         Help
"
  exit 1
}

unsetError=false
if [ -z ${DB_HOST+x} ]
then 
  cli_log "ERROR: DB_HOST is unset"
  unsetError=true
fi
if [ -z ${DB_USER+x} ]
then 
  cli_log "ERROR: DB_USER is unset"
  unsetError=true
fi
if [ -z ${DB_PASSWORD+x} ]
then 
  cli_log "ERROR: DB_PASSWORD is unset"
  unsetError=true
fi

if [ "$unsetError" = true ] ; then
    cli_log 'EXIT'
    exit 1
fi

case "$1" in
  create)
    "$DB_MANAGER_WORKDIR/commands/create" "$2"
    ;;
  exist)
    "$DB_MANAGER_WORKDIR/commands/exist" "$2"
    ;;
  view)
    "$DB_MANAGER_WORKDIR/commands/view" "$@"
  ;;
  restore)
    "$DB_MANAGER_WORKDIR/commands/restore" "$@"
  ;;
  sync)
    "$DB_MANAGER_WORKDIR/commands/sync" "$@"
  ;;
  user)
    "$DB_MANAGER_WORKDIR/commands/user" "$@"
  ;;
  access)
    "$DB_MANAGER_WORKDIR/commands/access" "$@"
  ;;
  drop)
    "$DB_MANAGER_WORKDIR/commands/drop" "$2"
  ;;
  *)
    cli_help
    ;;
esac