#!/usr/bin/env bash
set -e
. "$DB_MANAGER_WORKDIR/common"

shopt -s expand_aliases
source $DB_MANAGER_WORKDIR/aliases

cli_help_access() {
  echo "
Command: access
Description: Grant or revoke access of a user
Usage: 
  access grant <user> <database>
  access revoke <user> "
  exit 1
}


if [ -z "$2" ]
then
    cli_help_access
else
    echo ""
fi


if [[ "$#" -ne 4 && "$#" -ne 3 ]]; then
    cli_log "Illegal number of parameters"
    cli_help_access
fi

case "$2" in
  
  grant)

    export DB_NAME=$4
    export USER_NAME=$3

    if mshow $DB_NAME 2> /dev/null ; then
      cli_log "DB $DB_NAME exists"
    else
      cli_log "ERROR: DB $DB_NAME doesn't exist ..."
      exit 1
    fi

    RESULT_VARIABLE="$(msql -sse "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '$USER_NAME')")"
    if [ "$RESULT_VARIABLE" = 1 ]; then
      cli_log "User $USER_NAME exists"
    else
      cli_log "ERROR: User $USER_NAME doesn't exist"
      exit 1
    fi

    msql -e "GRANT ALL PRIVILEGES ON $DB_NAME. * TO '$USER_NAME'@'%';"

    if [ $? -eq 0 ]; then
        cli_log "Grant access done"
        exit 0
    else
        cli_log "ERROR: Grant access failed"
        exit 1
    fi
    ;;
  revoke)
    
    export USER_NAME=$3

    RESULT_VARIABLE="$(msql -sse "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '$USER_NAME')")"
    if [ "$RESULT_VARIABLE" = 1 ]; then
      cli_log "User $USER_NAME exists"
    else
      cli_log "ERROR: User $USER_NAME doesn't exist"
      exit 1
    fi

    msql -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '$USER_NAME'@'%';"
    if [ $? -eq 0 ]; then
        cli_log "Revoke access done"
        exit 0
    else
        cli_log "ERROR: Revoke access failed"
        exit 1
    fi
    ;;
  *)
    cli_help_access
    ;;  
esac