#!/usr/bin/env bash
set -e
. "$DB_MANAGER_WORKDIR/common"

shopt -s expand_aliases
source $DB_MANAGER_WORKDIR/aliases

cli_help_create() {
  echo "
Command: create
Description: create a database
Usage: 
  create <database>"
  exit 1
}

[ ! -n "$1" ] && cli_help_create

export DB_NAME=$1

cli_log "Create Database ..."

if mshow $DB_NAME 2> /dev/null ; then
  cli_log "DB ${DB_NAME} exists and can't be created"
  exit 1
else
  cli_log "DB ${DB_NAME} doesn't exist ..."
  msql -e "CREATE DATABASE $DB_NAME ;"
fi
cli_log "Creatition Done"
exit 0