#!/usr/bin/env bash
set -e
. "$DB_MANAGER_WORKDIR/common"

shopt -s expand_aliases
source $DB_MANAGER_WORKDIR/aliases

cli_help_drop() {
  echo "
Command: drop
Description: drop a database
Usage: 
  drop <database>"
  exit 1
}

[ ! -n "$1" ] && cli_help_drop

export DB_NAME=$1

cli_log "Drop Database ..."

if mshow $DB_NAME 2> /dev/null ; then
  cli_log "DB ${DB_NAME} exists"
else
  cli_log "DB ${DB_NAME} doesn't exist and can't be dropped"
  exit 1
fi

msql -e "DROP DATABASE ${DB_NAME};"
if [ $? -eq 0 ]; then
    cli_log "Database drop done"
    exit 0
else
    cli_log "ERROR: Database drop failed"
    exit 1
fi