#!/usr/bin/env bash
set -e
. "$DB_MANAGER_WORKDIR/common"

shopt -s expand_aliases
source $DB_MANAGER_WORKDIR/aliases

cli_help_exist() {
  echo "
Command: exist
Description: Does database exist
Usage: 
  exist <database>"
  exit 1
}

[ ! -n "$1" ] && cli_help_exist

export DB_NAME=$1

if mshow $DB_NAME 2> /dev/null ; then
  cli_log "DB ${DB_NAME} exists"
  exit 0
else
  cli_log "DB ${DB_NAME} doesn't exist"
  exit 1
fi

