#!/usr/bin/env bash
set -e
. "$DB_MANAGER_WORKDIR/common"

shopt -s expand_aliases
source $DB_MANAGER_WORKDIR/aliases

cli_help_restore() {
  echo "
Command: restore
Description: restore databases
Usage: 
  restore <database> <dumpfile> "
  exit 1
}

if [ -z "$2" ]
then
      cli_help_restore
else
      echo ""
fi

if [ "$#" -ne 3 ]; then
    cli_log "Illegal number of parameters"
    cli_help_restore
fi

case "$2" in
  --help)
    cli_help_restore
    ;;
  *)
    export DUMP=$3
    export DB_NAME=$2
    cli_log "Restore of Database ..."
    if [[ -f "$DUMP" ]]; then
      # Check if the DB Exists
      if mshow $DB_NAME 2> /dev/null ; then
        cli_log "DB $DB_NAME exists"
      else
        cli_log "DB $DB_NAME doesn't exist ..."
        cli_log "Create it before restore ..."
        msql -e "CREATE DATABASE $DB_NAME ;"
      fi
      cli_log "Restore $DB_NAME from $DUMP"
      msql $DB_NAME < $DUMP
      if [ $? -eq 0 ]; then
        cli_log "Restore Done"
        exit 0
      else
        cli_log "ERROR: Restore Failed"
        exit 1
      fi
    else
      cli_log "ERROR: File $DUMP doesn't exist"
      exit 1
    fi
    ;;
esac