#!/usr/bin/env bash
set -e
. "$DB_MANAGER_WORKDIR/common"

shopt -s expand_aliases
source $DB_MANAGER_WORKDIR/aliases

cli_help_view() {
  echo "
Command: view
Description: view databases and users
Usage: 
  view [databases,users]
  view tables <database>"
  exit 1
}

if [ -z "$2" ]
then
    cli_help_view
else
     echo ""
fi

if [[ "$#" -ne 2 && "$#" -ne 3 ]]; then
    cli_log "Illegal number of parameters"
    cli_help_view
fi

case "$2" in
  users)
    cli_log "Lists of Users ..."
    msql -e "SELECT User,Host FROM mysql.user;"
    ;;
  databases)
    cli_log "Lists of Databases ..."
    mshow
    ;;
  tables)
    export DB_NAME=$3
    cli_log "List Tabels of Database $DB_NAME"
    if mshow $DB_NAME 2> /dev/null ; then
      cli_log "DB $DB_NAME exists"
    else
      cli_log "ERROR: DB $DB_NAME doesn't exist ..."
      exit 1
    fi
  ;;
  *)
    cli_help_view
    ;;
esac


